### ISSUE TITLE
Windows issues

### ISSUE THREAD

**Issue by sirdodger** [dinomight/DatabaseBackup#1] opened 2012-10-13 20:55 UTC
There are a few place in the code where paths are joined using a forward slash.  That makes them fail on Windows, where the path separator is a "\".

Instead, you want to use Path.Combine().

I tried looking up the original maintainer, but couldn't find anything, and then stumbled on this.  I figured I would contribute instead of just fixing and rebuilding myself.

**Comment by dinomight** [comment] 2012-10-18 14:59
I'm actually running this on Windows and haven't had a crash yet.  Do you have any cases where this broke?  I can look into making the change since I'm a fan of being a bit more general about these kinds of things.

**Comment by sirdodger** [comment] 2012-10-19 17:38
I tried to get a repro of it failing, so of course it started working.  I'll keep an eye out for it breaking again.

That said, the best practice when building file paths is to always use the native OS path delimiter.  In C#, using the built-in Path.Combine() method does that.  If you look in the logfile on Windows, you can see the mixed delimiters:

e.g., C:\Foo/keys_20121019-103156.kdbx

**Comment by dinomight** [comment] 2012-10-19 17:45
Alright.  I'll go ahead and start looking into this.  Thanks for the report.

**Comment by dinomight** [comment] 2012-10-19 18:13
I did the swap, but I don't have any other environments to validate that the fix works for them too.  For the time being, I'm just gonna go ahead and close this.  If you are able to reproduce, don't hesitate to open this up again and I'll look deeper into the issue.

**Closed as completed by dinomight** 2012-10-19 18:13 UTC
